In [1]:
import pandas as pd

df = pd.read_csv("/content/ecommerce_sales.csv.csv")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 08:26,3.39,17850.0,United Kingdom

In [2]:
# dataset size
print("Dataset shape:", df.shape)

# column names
print("\nColumns:")
print(df.columns)

# data types
print("\nData types:")
print(df.dtypes)

Dataset shape: (199999, 8)

Columns:
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

Data types:
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [3]:
# check missing values
missing_values = df.isnull().sum()
missing_values

InvoiceNo          0
StockCode          0
Description      790
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     58014
Country            0
dtype: int64

In [4]:
# create revenue column
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

# preview
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 08:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 08:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 08:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 08:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 08:26,3.39,17850.0,United Kingdom,20.34

In [5]:
# check negative quantities (returns)
df[df["Quantity"] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
141,C536379,D,Discount,-1,12/1/2010 09:41,27.50,14527.0,United Kingdom,-27.50
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 09:49,4.65,15311.0,United Kingdom,-4.65
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom,-19.80
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom,-6.96
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom,-6.96

In [6]:
# remove returns and zero quantities
df_clean = df[df["Quantity"] > 0]

# remove rows with missing customer IDs
df_clean = df_clean.dropna(subset=["CustomerID"])

df_clean.shape

(138584, 9)

In [7]:
top_products = (
    df_clean.groupby("Description")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products

Description
MEDIUM CERAMIC TOP STORAGE JAR        77819.13
REGENCY CAKESTAND 3 TIER              74733.75
WHITE HANGING HEART T-LIGHT HOLDER    51440.80
POSTAGE                               33173.70
JUMBO BAG RED RETROSPOT               30835.90
PARTY BUNTING                         29218.15
ASSORTED COLOUR BIRD ORNAMENT         20801.50
CHILLI LIGHTS                         18992.96
VINTAGE UNION JACK MEMOBOARD          17811.33
Manual                                17026.64
Name: Revenue, dtype: float64

In [8]:
revenue_country = (
    df_clean.groupby("Country")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

revenue_country.head(10)

Country
United Kingdom    2586265.491
Netherlands        102130.580
Germany             90475.610
EIRE                84569.850
France              69812.380
Australia           55907.890
Spain               23095.830
Japan               21434.730
Sweden              16041.780
Switzerland         14841.850
Name: Revenue, dtype: float64

In [9]:
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])

monthly_revenue = (
    df_clean
    .groupby(df_clean["InvoiceDate"].dt.to_period("M"))["Revenue"]
    .sum()
)

monthly_revenue

InvoiceDate
2010-12    572713.890
2011-01    569445.040
2011-02    447137.350
2011-03    595500.760
2011-04    469200.361
2011-05    510102.460
Freq: M, Name: Revenue, dtype: float64